version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: caadocker/reverseproxy-v2
  backend_user:
    build:
      context: ../../udagram-api-user
    image: caadocker/api-user
  backend_feed:
    build:
      context: ../../udagram-api-feed
    image: caadocker/api-feed
  frontend:
    build:
      context: ../../udagram-frontend  
    image: caadocker/myproject